package lime.graphics.opengl.ext;

@:keep
@:noCompletion class ARB_shader_atomic_counters
{
	public var ATOMIC_COUNTER_BUFFER = 0x92C0;
	public var ATOMIC_COUNTER_BUFFER_BINDING = 0x92C1;
	public var ATOMIC_COUNTER_BUFFER_START = 0x92C2;
	public var ATOMIC_COUNTER_BUFFER_SIZE = 0x92C3;
	public var ATOMIC_COUNTER_BUFFER_DATA_SIZE = 0x92C4;
	public var ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTERS = 0x92C5;
	public var ATOMIC_COUNTER_BUFFER_ACTIVE_ATOMIC_COUNTER_INDICES = 0x92C6;
	public var ATOMIC_COUNTER_BUFFER_REFERENCED_BY_VERTEX_SHADER = 0x92C7;
	public var ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_CONTROL_SHADER = 0x92C8;
	public var ATOMIC_COUNTER_BUFFER_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x92C9;
	public var ATOMIC_COUNTER_BUFFER_REFERENCED_BY_GEOMETRY_SHADER = 0x92CA;
	public var ATOMIC_COUNTER_BUFFER_REFERENCED_BY_FRAGMENT_SHADER = 0x92CB;
	public var MAX_VERTEX_ATOMIC_COUNTER_BUFFERS = 0x92CC;
	public var MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS = 0x92CD;
	public var MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS = 0x92CE;
	public var MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS = 0x92CF;
	public var MAX_FRAGMENT_ATOMIC_COUNTER_BUFFERS = 0x92D0;
	public var MAX_COMBINED_ATOMIC_COUNTER_BUFFERS = 0x92D1;
	public var MAX_VERTEX_ATOMIC_COUNTERS = 0x92D2;
	public var MAX_TESS_CONTROL_ATOMIC_COUNTERS = 0x92D3;
	public var MAX_TESS_EVALUATION_ATOMIC_COUNTERS = 0x92D4;
	public var MAX_GEOMETRY_ATOMIC_COUNTERS = 0x92D5;
	public var MAX_FRAGMENT_ATOMIC_COUNTERS = 0x92D6;
	public var MAX_COMBINED_ATOMIC_COUNTERS = 0x92D7;
	public var MAX_ATOMIC_COUNTER_BUFFER_SIZE = 0x92D8;
	public var MAX_ATOMIC_COUNTER_BUFFER_BINDINGS = 0x92DC;
	public var ACTIVE_ATOMIC_COUNTER_BUFFERS = 0x92D9;
	public var UNIFORM_ATOMIC_COUNTER_BUFFER_INDEX = 0x92DA;
	public var UNSIGNED_INT_ATOMIC_COUNTER = 0x92DB;

	@:noCompletion private function new() {}

	// void glGetActiveAtomicCounterBufferiv (GLuint program, GLuint bufferIndex, GLenum pname, GLint *params)
}
