package lime.graphics.opengl.ext;

@:keep
@:noCompletion class EXT_geometry_shader
{
	public var GEOMETRY_SHADER_EXT = 0x8DD9;
	public var GEOMETRY_SHADER_BIT_EXT = 0x00000004;
	public var GEOMETRY_LINKED_VERTICES_OUT_EXT = 0x8916;
	public var GEOMETRY_LINKED_INPUT_TYPE_EXT = 0x8917;
	public var GEOMETRY_LINKED_OUTPUT_TYPE_EXT = 0x8918;
	public var GEOMETRY_SHADER_INVOCATIONS_EXT = 0x887F;
	public var LAYER_PROVOKING_VERTEX_EXT = 0x825E;
	public var LINES_ADJACENCY_EXT = 0x000A;
	public var LINE_STRIP_ADJACENCY_EXT = 0x000B;
	public var TRIANGLES_ADJACENCY_EXT = 0x000C;
	public var TRIANGLE_STRIP_ADJACENCY_EXT = 0x000D;
	public var MAX_GEOMETRY_UNIFORM_COMPONENTS_EXT = 0x8DDF;
	public var MAX_GEOMETRY_UNIFORM_BLOCKS_EXT = 0x8A2C;
	public var MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS_EXT = 0x8A32;
	public var MAX_GEOMETRY_INPUT_COMPONENTS_EXT = 0x9123;
	public var MAX_GEOMETRY_OUTPUT_COMPONENTS_EXT = 0x9124;
	public var MAX_GEOMETRY_OUTPUT_VERTICES_EXT = 0x8DE0;
	public var MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS_EXT = 0x8DE1;
	public var MAX_GEOMETRY_SHADER_INVOCATIONS_EXT = 0x8E5A;
	public var MAX_GEOMETRY_TEXTURE_IMAGE_UNITS_EXT = 0x8C29;
	public var MAX_GEOMETRY_ATOMIC_COUNTER_BUFFERS_EXT = 0x92CF;
	public var MAX_GEOMETRY_ATOMIC_COUNTERS_EXT = 0x92D5;
	public var MAX_GEOMETRY_IMAGE_UNIFORMS_EXT = 0x90CD;
	public var MAX_GEOMETRY_SHADER_STORAGE_BLOCKS_EXT = 0x90D7;
	public var FIRST_VERTEX_CONVENTION_EXT = 0x8E4D;
	public var LAST_VERTEX_CONVENTION_EXT = 0x8E4E;
	public var UNDEFINED_VERTEX_EXT = 0x8260;
	public var PRIMITIVES_GENERATED_EXT = 0x8C87;
	public var FRAMEBUFFER_DEFAULT_LAYERS_EXT = 0x9312;
	public var MAX_FRAMEBUFFER_LAYERS_EXT = 0x9317;
	public var FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS_EXT = 0x8DA8;
	public var FRAMEBUFFER_ATTACHMENT_LAYERED_EXT = 0x8DA7;
	public var REFERENCED_BY_GEOMETRY_SHADER_EXT = 0x9309;

	@:noCompletion private function new() {}

	// void glFramebufferTextureEXT (GLenum target, GLenum attachment, GLuint texture, GLint level)
}
