package lime.graphics.opengl.ext;

@:keep
@:noCompletion class EXT_fragment_shading_rate
{
	public var SHADING_RATE_1X1_PIXELS_EXT = 0x96A6;
	public var SHADING_RATE_1X2_PIXELS_EXT = 0x96A7;
	public var SHADING_RATE_2X1_PIXELS_EXT = 0x96A8;
	public var SHADING_RATE_2X2_PIXELS_EXT = 0x96A9;
	public var SHADING_RATE_1X4_PIXELS_EXT = 0x96AA;
	public var SHADING_RATE_4X1_PIXELS_EXT = 0x96AB;
	public var SHADING_RATE_4X2_PIXELS_EXT = 0x96AC;
	public var SHADING_RATE_2X4_PIXELS_EXT = 0x96AD;
	public var SHADING_RATE_4X4_PIXELS_EXT = 0x96AE;
	public var SHADING_RATE_EXT = 0x96D0;
	public var SHADING_RATE_ATTACHMENT_EXT = 0x96D1;
	public var FRAGMENT_SHADING_RATE_COMBINER_OP_KEEP_EXT = 0x96D2;
	public var FRAGMENT_SHADING_RATE_COMBINER_OP_REPLACE_EXT = 0x96D3;
	public var FRAGMENT_SHADING_RATE_COMBINER_OP_MIN_EXT = 0x96D4;
	public var FRAGMENT_SHADING_RATE_COMBINER_OP_MAX_EXT = 0x96D5;
	public var FRAGMENT_SHADING_RATE_COMBINER_OP_MUL_EXT = 0x96D6;
	public var MIN_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_WIDTH_EXT = 0x96D7;
	public var MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_WIDTH_EXT = 0x96D8;
	public var MIN_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_HEIGHT_EXT = 0x96D9;
	public var MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_HEIGHT_EXT = 0x96DA;
	public var MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_TEXEL_ASPECT_RATIO_EXT = 0x96DB;
	public var MAX_FRAGMENT_SHADING_RATE_ATTACHMENT_LAYERS_EXT = 0x96DC;
	public var FRAGMENT_SHADING_RATE_WITH_SHADER_DEPTH_STENCIL_WRITES_SUPPORTED_EXT = 0x96DD;
	public var FRAGMENT_SHADING_RATE_WITH_SAMPLE_MASK_SUPPORTED_EXT = 0x96DE;
	public var FRAGMENT_SHADING_RATE_ATTACHMENT_WITH_DEFAULT_FRAMEBUFFER_SUPPORTED_EXT = 0x96DF;
	public var FRAGMENT_SHADING_RATE_NON_TRIVIAL_COMBINERS_SUPPORTED_EXT = 0x8F6F;

	@:noCompletion private function new() {}

	// void glGetFragmentShadingRatesEXT (GLsizei samples, GLsizei maxCount, GLsizei *count, GLenum *shadingRates)
	// void glShadingRateEXT (GLenum rate)
	// void glShadingRateCombinerOpsEXT (GLenum combinerOp0, GLenum combinerOp1)
	// void glFramebufferShadingRateEXT (GLenum target, GLenum attachment, GLuint texture, GLint baseLayer, GLsizei numLayers, GLsizei texelWidth, GLsizei texelHeight)
}
