package lime.graphics.opengl.ext;

@:keep
@:noCompletion class EXT_mesh_shader
{
	public var MESH_SHADER_EXT = 0x9559;
	public var TASK_SHADER_EXT = 0x955A;
	public var MAX_MESH_UNIFORM_BLOCKS_EXT = 0x8E60;
	public var MAX_MESH_TEXTURE_IMAGE_UNITS_EXT = 0x8E61;
	public var MAX_MESH_IMAGE_UNIFORMS_EXT = 0x8E62;
	public var MAX_MESH_UNIFORM_COMPONENTS_EXT = 0x8E63;
	public var MAX_MESH_ATOMIC_COUNTER_BUFFERS_EXT = 0x8E64;
	public var MAX_MESH_ATOMIC_COUNTERS_EXT = 0x8E65;
	public var MAX_MESH_SHADER_STORAGE_BLOCKS_EXT = 0x8E66;
	public var MAX_COMBINED_MESH_UNIFORM_COMPONENTS_EXT = 0x8E67;
	public var MAX_TASK_UNIFORM_BLOCKS_EXT = 0x8E68;
	public var MAX_TASK_TEXTURE_IMAGE_UNITS_EXT = 0x8E69;
	public var MAX_TASK_IMAGE_UNIFORMS_EXT = 0x8E6A;
	public var MAX_TASK_UNIFORM_COMPONENTS_EXT = 0x8E6B;
	public var MAX_TASK_ATOMIC_COUNTER_BUFFERS_EXT = 0x8E6C;
	public var MAX_TASK_ATOMIC_COUNTERS_EXT = 0x8E6D;
	public var MAX_TASK_SHADER_STORAGE_BLOCKS_EXT = 0x8E6E;
	public var MAX_COMBINED_TASK_UNIFORM_COMPONENTS_EXT = 0x8E6F;
	public var MAX_TASK_WORK_GROUP_TOTAL_COUNT_EXT = 0x9740;
	public var MAX_MESH_WORK_GROUP_TOTAL_COUNT_EXT = 0x9741;
	public var MAX_MESH_WORK_GROUP_INVOCATIONS_EXT = 0x9757;
	public var MAX_TASK_WORK_GROUP_INVOCATIONS_EXT = 0x9759;
	public var MAX_TASK_PAYLOAD_SIZE_EXT = 0x9742;
	public var MAX_TASK_SHARED_MEMORY_SIZE_EXT = 0x9743;
	public var MAX_MESH_SHARED_MEMORY_SIZE_EXT = 0x9744;
	public var MAX_TASK_PAYLOAD_AND_SHARED_MEMORY_SIZE_EXT = 0x9745;
	public var MAX_MESH_PAYLOAD_AND_SHARED_MEMORY_SIZE_EXT = 0x9746;
	public var MAX_MESH_OUTPUT_MEMORY_SIZE_EXT = 0x9747;
	public var MAX_MESH_PAYLOAD_AND_OUTPUT_MEMORY_SIZE_EXT = 0x9748;
	public var MAX_MESH_OUTPUT_VERTICES_EXT = 0x9538;
	public var MAX_MESH_OUTPUT_PRIMITIVES_EXT = 0x9756;
	public var MAX_MESH_OUTPUT_COMPONENTS_EXT = 0x9749;
	public var MAX_MESH_OUTPUT_LAYERS_EXT = 0x974A;
	public var MAX_MESH_MULTIVIEW_VIEW_COUNT_EXT = 0x9557;
	public var MESH_OUTPUT_PER_VERTEX_GRANULARITY_EXT = 0x92DF;
	public var MESH_OUTPUT_PER_PRIMITIVE_GRANULARITY_EXT = 0x9543;
	public var MAX_PREFERRED_TASK_WORK_GROUP_INVOCATIONS_EXT = 0x974B;
	public var MAX_PREFERRED_MESH_WORK_GROUP_INVOCATIONS_EXT = 0x974C;
	public var MESH_PREFERS_LOCAL_INVOCATION_VERTEX_OUTPUT_EXT = 0x974D;
	public var MESH_PREFERS_LOCAL_INVOCATION_PRIMITIVE_OUTPUT_EXT = 0x974E;
	public var MESH_PREFERS_COMPACT_VERTEX_OUTPUT_EXT = 0x974F;
	public var MESH_PREFERS_COMPACT_PRIMITIVE_OUTPUT_EXT = 0x9750;
	public var MAX_TASK_WORK_GROUP_COUNT_EXT = 0x9751;
	public var MAX_MESH_WORK_GROUP_COUNT_EXT = 0x9752;
	public var MAX_MESH_WORK_GROUP_SIZE_EXT = 0x9758;
	public var MAX_TASK_WORK_GROUP_SIZE_EXT = 0x975A;
	public var MESH_WORK_GROUP_SIZE_EXT = 0x953E;
	public var TASK_WORK_GROUP_SIZE_EXT = 0x953F;
	public var MESH_VERTICES_OUT_EXT = 0x9579;
	public var MESH_PRIMITIVES_OUT_EXT = 0x957A;
	public var MESH_OUTPUT_TYPE_EXT = 0x957B;
	public var UNIFORM_BLOCK_REFERENCED_BY_MESH_SHADER_EXT = 0x959C;
	public var UNIFORM_BLOCK_REFERENCED_BY_TASK_SHADER_EXT = 0x959D;
	public var REFERENCED_BY_MESH_SHADER_EXT = 0x95A0;
	public var REFERENCED_BY_TASK_SHADER_EXT = 0x95A1;
	public var TASK_SHADER_INVOCATIONS_EXT = 0x9753;
	public var MESH_SHADER_INVOCATIONS_EXT = 0x9754;
	public var MESH_PRIMITIVES_GENERATED_EXT = 0x9755;
	public var MESH_SHADER_BIT_EXT = 0x00000040;
	public var TASK_SHADER_BIT_EXT = 0x00000080;

	@:noCompletion private function new() {}

	// void glDrawMeshTasksEXT (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z)
	// void glDrawMeshTasksIndirectEXT (GLintptr indirect)
	// void glMultiDrawMeshTasksIndirectEXT (GLintptr indirect, GLsizei drawcount, GLsizei stride)
}
