package lime.graphics.opengl.ext;

@:keep
@:noCompletion class NV_texture_shader3
{
	public var OFFSET_PROJECTIVE_TEXTURE_2D_NV = 0x8850;
	public var OFFSET_PROJECTIVE_TEXTURE_2D_SCALE_NV = 0x8851;
	public var OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_NV = 0x8852;
	public var OFFSET_PROJECTIVE_TEXTURE_RECTANGLE_SCALE_NV = 0x8853;
	public var OFFSET_HILO_TEXTURE_2D_NV = 0x8854;
	public var OFFSET_HILO_TEXTURE_RECTANGLE_NV = 0x8855;
	public var OFFSET_HILO_PROJECTIVE_TEXTURE_2D_NV = 0x8856;
	public var OFFSET_HILO_PROJECTIVE_TEXTURE_RECTANGLE_NV = 0x8857;
	public var DEPENDENT_HILO_TEXTURE_2D_NV = 0x8858;
	public var DEPENDENT_RGB_TEXTURE_3D_NV = 0x8859;
	public var DEPENDENT_RGB_TEXTURE_CUBE_MAP_NV = 0x885A;
	public var DOT_PRODUCT_PASS_THROUGH_NV = 0x885B;
	public var DOT_PRODUCT_TEXTURE_1D_NV = 0x885C;
	public var DOT_PRODUCT_AFFINE_DEPTH_REPLACE_NV = 0x885D;
	public var HILO8_NV = 0x885E;
	public var SIGNED_HILO8_NV = 0x885F;
	public var FORCE_BLUE_TO_ONE_NV = 0x8860;

	@:noCompletion private function new() {}
}
