package lime.graphics.opengl.ext;

@:keep
@:noCompletion class OES_tessellation_shader
{
	public var PATCHES_OES = 0x000E;
	public var PATCH_VERTICES_OES = 0x8E72;
	public var TESS_CONTROL_OUTPUT_VERTICES_OES = 0x8E75;
	public var TESS_GEN_MODE_OES = 0x8E76;
	public var TESS_GEN_SPACING_OES = 0x8E77;
	public var TESS_GEN_VERTEX_ORDER_OES = 0x8E78;
	public var TESS_GEN_POINT_MODE_OES = 0x8E79;
	public var TRIANGLES = 0x0004;
	public var ISOLINES_OES = 0x8E7A;
	public var QUADS_OES = 0x0007;
	public var EQUAL = 0x0202;
	public var FRACTIONAL_ODD_OES = 0x8E7B;
	public var FRACTIONAL_EVEN_OES = 0x8E7C;
	public var CCW = 0x0901;
	public var CW = 0x0900;
	public var MAX_PATCH_VERTICES_OES = 0x8E7D;
	public var MAX_TESS_GEN_LEVEL_OES = 0x8E7E;
	public var MAX_TESS_CONTROL_UNIFORM_COMPONENTS_OES = 0x8E7F;
	public var MAX_TESS_EVALUATION_UNIFORM_COMPONENTS_OES = 0x8E80;
	public var MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS_OES = 0x8E81;
	public var MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS_OES = 0x8E82;
	public var MAX_TESS_CONTROL_OUTPUT_COMPONENTS_OES = 0x8E83;
	public var MAX_TESS_PATCH_COMPONENTS_OES = 0x8E84;
	public var MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS_OES = 0x8E85;
	public var MAX_TESS_EVALUATION_OUTPUT_COMPONENTS_OES = 0x8E86;
	public var MAX_TESS_CONTROL_UNIFORM_BLOCKS_OES = 0x8E89;
	public var MAX_TESS_EVALUATION_UNIFORM_BLOCKS_OES = 0x8E8A;
	public var MAX_TESS_CONTROL_INPUT_COMPONENTS_OES = 0x886C;
	public var MAX_TESS_EVALUATION_INPUT_COMPONENTS_OES = 0x886D;
	public var MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS_OES = 0x8E1E;
	public var MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS_OES = 0x8E1F;
	public var MAX_TESS_CONTROL_ATOMIC_COUNTER_BUFFERS_OES = 0x92CD;
	public var MAX_TESS_EVALUATION_ATOMIC_COUNTER_BUFFERS_OES = 0x92CE;
	public var MAX_TESS_CONTROL_ATOMIC_COUNTERS_OES = 0x92D3;
	public var MAX_TESS_EVALUATION_ATOMIC_COUNTERS_OES = 0x92D4;
	public var MAX_TESS_CONTROL_IMAGE_UNIFORMS_OES = 0x90CB;
	public var MAX_TESS_EVALUATION_IMAGE_UNIFORMS_OES = 0x90CC;
	public var MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS_OES = 0x90D8;
	public var MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS_OES = 0x90D9;
	public var PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED_OES = 0x8221;
	public var IS_PER_PATCH_OES = 0x92E7;
	public var REFERENCED_BY_TESS_CONTROL_SHADER_OES = 0x9307;
	public var REFERENCED_BY_TESS_EVALUATION_SHADER_OES = 0x9308;
	public var TESS_CONTROL_SHADER_OES = 0x8E88;
	public var TESS_EVALUATION_SHADER_OES = 0x8E87;
	public var TESS_CONTROL_SHADER_BIT_OES = 0x00000008;
	public var TESS_EVALUATION_SHADER_BIT_OES = 0x00000010;

	@:noCompletion private function new() {}

	// void glPatchParameteriOES (GLenum pname, GLint value)
}
